// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB47W0qcoLbJHPc49VdHCn_USBSUGcq-Ew',
    appId: '1:27185907628:web:b630d4821bd8a08b6d5c09',
    messagingSenderId: '27185907628',
    projectId: 'tasksorganizer-51db3',
    authDomain: 'tasksorganizer-51db3.firebaseapp.com',
    storageBucket: 'tasksorganizer-51db3.appspot.com',
    measurementId: 'G-XSV2L0XP62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD187s_SL6lAwx1s8WAW2ifcyBgUy5Nelo',
    appId: '1:27185907628:android:e1ae8a3da3dc300c6d5c09',
    messagingSenderId: '27185907628',
    projectId: 'tasksorganizer-51db3',
    storageBucket: 'tasksorganizer-51db3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArq82vs_asXPILVGiPUpAaXIxvqGfGk9k',
    appId: '1:27185907628:ios:36afc591e4b20e306d5c09',
    messagingSenderId: '27185907628',
    projectId: 'tasksorganizer-51db3',
    storageBucket: 'tasksorganizer-51db3.appspot.com',
    iosBundleId: 'com.example.tasksOrganizer',
  );
}
